import type { App, Plugin } from 'vue';
import { installConfigManager, installDefaultsManager, installThemeManager } from '@vuecs/core';
import type { CoreOptions } from '@vuecs/core';

import './vue';
import { registerOverlayConfigDefaults } from './config';
import {
    AlertDialogManager,
    ToastManager,
    VCAlertDialog,
    VCAlertDialogAction,
    VCAlertDialogCancel,
    VCAlertDialogContent,
    VCAlertDialogDescription,
    VCAlertDialogProvider,
    VCAlertDialogTitle,
    VCAlertDialogTrigger,
    VCContextMenu,
    VCContextMenuCheckboxItem,
    VCContextMenuContent,
    VCContextMenuGroup,
    VCContextMenuItem,
    VCContextMenuItemIndicator,
    VCContextMenuLabel,
    VCContextMenuRadioGroup,
    VCContextMenuRadioItem,
    VCContextMenuSeparator,
    VCContextMenuSub,
    VCContextMenuSubContent,
    VCContextMenuSubTrigger,
    VCContextMenuTrigger,
    VCDropdownMenu,
    VCDropdownMenuArrow,
    VCDropdownMenuCheckboxItem,
    VCDropdownMenuContent,
    VCDropdownMenuGroup,
    VCDropdownMenuItem,
    VCDropdownMenuItemIndicator,
    VCDropdownMenuLabel,
    VCDropdownMenuRadioGroup,
    VCDropdownMenuRadioItem,
    VCDropdownMenuSeparator,
    VCDropdownMenuSub,
    VCDropdownMenuSubContent,
    VCDropdownMenuSubTrigger,
    VCDropdownMenuTrigger,
    VCHoverCard,
    VCHoverCardArrow,
    VCHoverCardContent,
    VCHoverCardTrigger,
    VCModal,
    VCModalClose,
    VCModalContent,
    VCModalDescription,
    VCModalTitle,
    VCModalTrigger,
    VCPopover,
    VCPopoverArrow,
    VCPopoverClose,
    VCPopoverContent,
    VCPopoverTrigger,
    VCPresence,
    VCToast,
    VCToastAction,
    VCToastClose,
    VCToastDescription,
    VCToastProvider,
    VCToastTitle,
    VCToaster,
    VCTooltip,
    VCTooltipArrow,
    VCTooltipContent,
    VCTooltipProvider,
    VCTooltipTrigger,
    provideAlertDialogManager,
    provideToastManager,
} from './components';

export * from './components';

export type Options = CoreOptions;

export function install(app: App, options: Options = {}): void {
    installThemeManager(app, options);
    installDefaultsManager(app, options);
    const config = installConfigManager(app, options);
    registerOverlayConfigDefaults(config);

    // App-scoped imperative queues (toast + confirm) — one manager per app so
    // concurrent SSR requests never share state and multi-app pages stay
    // isolated. `useToast()` / `useAlertDialog()` and their hosts inject these.
    provideToastManager(new ToastManager(), app);
    provideAlertDialogManager(new AlertDialogManager(), app);

    Object.entries({
        VCPresence,
        VCAlertDialog,
        VCAlertDialogTrigger,
        VCAlertDialogContent,
        VCAlertDialogTitle,
        VCAlertDialogDescription,
        VCAlertDialogCancel,
        VCAlertDialogAction,
        VCAlertDialogProvider,
        VCModal,
        VCModalTrigger,
        VCModalContent,
        VCModalTitle,
        VCModalDescription,
        VCModalClose,
        VCPopover,
        VCPopoverTrigger,
        VCPopoverContent,
        VCPopoverArrow,
        VCPopoverClose,
        VCTooltipProvider,
        VCTooltip,
        VCTooltipTrigger,
        VCTooltipContent,
        VCTooltipArrow,
        VCDropdownMenu,
        VCDropdownMenuTrigger,
        VCDropdownMenuContent,
        VCDropdownMenuItem,
        VCDropdownMenuCheckboxItem,
        VCDropdownMenuRadioGroup,
        VCDropdownMenuRadioItem,
        VCDropdownMenuItemIndicator,
        VCDropdownMenuLabel,
        VCDropdownMenuSeparator,
        VCDropdownMenuGroup,
        VCDropdownMenuSub,
        VCDropdownMenuSubTrigger,
        VCDropdownMenuSubContent,
        VCDropdownMenuArrow,
        VCHoverCard,
        VCHoverCardTrigger,
        VCHoverCardContent,
        VCHoverCardArrow,
        VCContextMenu,
        VCContextMenuTrigger,
        VCContextMenuContent,
        VCContextMenuItem,
        VCContextMenuCheckboxItem,
        VCContextMenuRadioGroup,
        VCContextMenuRadioItem,
        VCContextMenuItemIndicator,
        VCContextMenuLabel,
        VCContextMenuSeparator,
        VCContextMenuGroup,
        VCContextMenuSub,
        VCContextMenuSubTrigger,
        VCContextMenuSubContent,
        VCToastProvider,
        VCToaster,
        VCToast,
        VCToastTitle,
        VCToastDescription,
        VCToastAction,
        VCToastClose,
    }).forEach(([name, component]) => {
        app.component(name, component);
    });
}

export default { install } satisfies Plugin<[Options?]>;
